Implement the new structure of the match object for changed files section
akv-platform/labeler pull request #5
Opened 2023-09-04 16:08 UTC by MaksimZhukov

**Description:**
In scope of this pull request, the structure of the configuration file (`.github/labeler.yml`) was changed from
```yml
LabelName:
- any:
  - changed-files: ['list', 'of', 'globs']
  - base-branch: ['list', 'of', 'regexps']
  - head-branch: ['list', 'of', 'regexps']
- all:
  - changed-files: ['list', 'of', 'globs']
  - base-branch: ['list', 'of', 'regexps']
  - head-branch: ['list', 'of', 'regexps']
```
to
```yml
LabelName:
- any:
  - changed-files: 
    - AnyGlobToAnyFile: ['list', 'of', 'globs']
    - AnyGlobToAllFiles: ['list', 'of', 'globs']
    - AllGlobsToAnyFile: ['list', 'of', 'globs']
    - AllGlobsToAllFiles: ['list', 'of', 'globs']
  - base-branch: ['list', 'of', 'regexps']
  - head-branch: ['list', 'of', 'regexps']
- all:
  - changed-files:
    - AnyGlobToAnyFile: ['list', 'of', 'globs']
    - AnyGlobToAllFiles: ['list', 'of', 'globs']
    - AllGlobsToAnyFile: ['list', 'of', 'globs']
    - AllGlobsToAllFiles: ['list', 'of', 'globs']
  - base-branch: ['list', 'of', 'regexps']
  - head-branch: ['list', 'of', 'regexps']
```

In the previous implementation of the beta version, customers had two options: `any` (ANY glob must match against ANY changed file) and `all` (ALL globs must match against ALL changed files). In scope of this PR, we expanded this functionality and provided customers with all possible combinations:
1) `AnyGlobToAnyFile` - ANY glob must match against ANY changed file
2) `AllGlobsToAnyFile` - ALL globs must match against ANY changed file
3) `AnyGlobToAllFiles` - ANY glob must match against ALL changed files
4) `AllGlobsToAllFiles` - ALL globs must match against ALL changed files

2023-09-06 08:00 UTC, dsame approved these changes
Some code improvements are suggested, none of them prevents PR from merge.

2023-09-06 08:00 UTC, dsame commented on src/changedFiles.ts
> +      throw new Error(
May be it worth to skip the invalid keys and continue the processing with a warning.

2023-09-06 08:00 UTC, dsame commented on src/changedFiles.ts
> +  });
i would try to refactor is with immutable way like this:

```
 validChangedFilesConfigs = Object.keys(changedFilesConfig).filter(key => {
  if (invalidKey) {
    warn ...
    return false;
  }
  return true;
  }).reduce((arr, key) => {
    arr.push(changedFilesConfig[key]);
    return arr;
  }, []);
```

2023-09-06 08:00 UTC, dsame commented on src/changedFiles.ts
> +  for (const matcher of matchers) {
i'd replaced it with `(const matcher of globs.map(g => new Minimatch(g)))` because `matchers` is not used anymore

2023-09-06 08:00 UTC, dsame commented on src/changedFiles.ts
> +        break;
i'd try to replace `for ... break` with `changedFiles.find( ... )` because for "any" check it is enough to find at least one first match and "find" is semantically more corresponding with the "finding any match" task.

2023-09-06 08:00 UTC, dsame commented on src/changedFiles.ts
>    for (const changedFile of changedFiles) {
for "all" conditions i'd use `Array.find` with "!matched" exit condition

2023-09-08 11:37 UTC, nikolai-laevskii requested changes

2023-09-08 11:37 UTC, nikolai-laevskii commented on src/changedFiles.ts
> +    const invalidKeys = changedFilesConfigKeys.filter(
If intention was to throw error on any number of invalid keys, this could be replaced with `.find`, this way the rest of the array won't be iterated.

2023-09-08 11:37 UTC, nikolai-laevskii commented on src/changedFiles.ts
> +function isObject(obj: any): boolean {
```typescript
function isObject(obj: unknown): obj is object { /* ... */ }
```
или даже:
```typescript
function isRecord(obj: unknown): obj is Record<string | number | symbol, unknown> { /* ... */ }
```

2023-09-17 14:21 UTC, MaksimZhukov commented on src/changedFiles.ts
> +      throw new Error(
I thought about this too, but came to the conclusion that if we only warn users and continue with the wrong key, there is a chance that the label will be added to the PR, even if it is not added when the keys are correct. The keys depend on each other, so mistakes in the configuration file can lead to undesirable results. I prefer to abort execution and force users to fix their configuration files.

2023-09-17 14:24 UTC, MaksimZhukov commented on src/changedFiles.ts
> +  });
I prefer to avoid call chains due to unreadability. The current implementation looks much easier to read and understand than the proposed one.

2023-09-17 14:25 UTC, MaksimZhukov commented on src/changedFiles.ts
> +  for (const matcher of matchers) {
I prefer to keep the current implementation due to readability.

2023-09-17 14:28 UTC, MaksimZhukov commented on src/changedFiles.ts
> +        break;
Great point, thanks! Fixed. It's much more readable now

2023-09-17 14:28 UTC, MaksimZhukov commented on src/changedFiles.ts
>    for (const changedFile of changedFiles) {
Great point, thanks! Fixed. It's much more readable now

2023-09-17 14:29 UTC, MaksimZhukov commented on src/changedFiles.ts
> +    const invalidKeys = changedFilesConfigKeys.filter(
Explanation is in [this comment](https://github.com/akv-platform/labeler/pull/5#discussion_r1328100198)

2023-09-17 14:29 UTC, MaksimZhukov commented on src/changedFiles.ts
> +function isObject(obj: any): boolean {
Good point, thanks! Fixed

2023-09-18 10:58 UTC, dmitry-shibanov approved these changes

2023-09-18 13:01 UTC, nikolai-laevskii approved these changes

2023-09-19 14:54 UTC, IvanZosimov approved these changes

2023-09-20 09:59 UTC, marko-zivic-93 approved these changes

2023-09-20 12:03 UTC, closed without merging